# -*- coding: utf-8 -*-
"""Module_4_Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ucSup9gSMSz7T4NiBSNIXIQqR8uqoj9
"""

import pandas as pd

file_path = 'Netflix_data.csv'
try:
    df = pd.read_csv(file_path)
    print(f"Successfully loaded {file_path}")
    print("First 5 rows of the DataFrame:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please ensure it is uploaded to your Colab environment.")
except Exception as e:
    print(f"An error occurred while loading the file: {e}")

Netflix_shows_movies = df

Netflix_shows_movies.isnull().sum()

Netflix_shows_movies['director'].fillna('Unknown', inplace=True)
Netflix_shows_movies['cast'].fillna('Unknown', inplace=True)
Netflix_shows_movies['country'].fillna('Unknown', inplace=True)
Netflix_shows_movies['rating'].fillna('Unknown', inplace=True)
Netflix_shows_movies['date_added'].fillna('Unknown', inplace=True)

Netflix_shows_movies.isnull().sum()

Netflix_shows_movies.describe()

Netflix_shows_movies['type'].value_counts()

Netflix_shows_movies['rating'].value_counts()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))

sns.countplot(
    y='rating',
    data=Netflix_shows_movies,
    order=Netflix_shows_movies['rating'].value_counts().index
)

plt.title("Distribution of Netflix Ratings")
plt.xlabel("Count")
plt.ylabel("Rating")

plt.show()

genres = Netflix_shows_movies['listed_in'].str.split(',', expand=True).stack()

top_genres = genres.value_counts().head(10)

plt.figure(figsize=(10, 6))

top_genres.plot(kind='bar')

plt.title("Top 10 Most Popular Netflix Genres")
plt.xlabel("Genre")
plt.ylabel("Number of Titles")

plt.xticks(rotation=45)

plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%R -i Netflix_shows_movies
# library(ggplot2)
# library(readr)
# 
# # Assuming Netflix_shows_movies is already a DataFrame in R from the -i flag
# 
# print(ggplot(Netflix_shows_movies, aes(x = rating)) +
#   geom_bar(fill = "red") +
#   coord_flip() +
#   labs(
#       title = "Distribution of Netflix Ratings",
#        x = "Rating",
#        y = "Count"
#   ))